### ISSUE TITLE
URL field on basic guestbook doesn't allow valid url

### ISSUE THREAD

**Issue by pietvanzoen** [sarajw/sarawallen-astro#2]
<img width="582" alt="image" src="https://github.com/sarajw/sarawallen-astro/assets/630334/f42f503c-01a6-4797-ba3f-0b11121610be">

Managed to post on the regular (not basic?) site. 

https://github.com/sarajw/sarawallen-astro/blob/main/src/pages/guestbook.astro#L61

**Comment by sarajw** [comment]
Oh, that's so weird. As far as I know I basically copied and pasted the whole thing - I'll try and find out what's going on! Thanks for the heads up :)

**Comment by sarajw** [comment]
Sorted, a full stop was deleted which upset it! Should work now... Have also made it accept http:// URLs plus that button wasn't very satisfying to click...
